### PR TITLE
chore: update to use more competitive fees

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1220725976)

Uses a higher fee rate, hard coded for time being, but to be replaced endpoint described in this issue https://github.com/blockstack/stacks-blockchain-api/issues/729

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]

**Comment by Eshwari007** [comment]
@kyranjamie 
Here are my findings upon testing:
I do not see the setting option as we see in WW and testing concludes hard coded value as fee.
Attaching the screenshot for your input if this is as per design
Screen Shot 2021-09-08 at 4 49 13 PM
Screen Shot 2021-09-08 at 4 49 26 PM

**Comment by kyranjamie** [comment]
@Eshwari007 This PR doesn't intend on adding a custom fee selection element, like the web wallet. Just make them higher.

To QA, we need to broadcast the transactions and ensure the fee is the same when viewing the transaction in the explorer.

**Comment by Eshwari007** [comment]
Test passed.Moving it to Done

**Comment by kyranjamie** [comment]
@Eshwari007 why did you close this pull request? 🤔

**Comment by Eshwari007** [comment]
Am sorry -I was testing the build from here hence might have accidentally done so.

**Pull request merged**
