### PR TITLE
feat: adds update prompts, closes #274

### LINKED ISSUE #274: Add prompt for automatic updates
We should include the ability for the new Stacks Wallet to prompt the user upon load whenever there is a new version available, informing them of the changelog and giving them the option to install the update and restart the wallet.

@kyranjamie is design guidance necessary here or can you use standard elements?

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/460827823)

image

In mainnet mode, only the `Update available` message will be present.

Testnet will filter for the latest prerelease release, mainnet excludes prereleases.

### CODE REVIEW

**Comment by markmhx** [comment]
How's best to test this? Install and wait for next release to see if "Update available" shows up?

**Comment by markmhx** [comment]
@kyranjamie nudge about https://github.com/blockstack/stacks-wallet/pull/418#issuecomment-749276570

**Comment by kyranjamie** [comment]
Yes, sorry. Now that there are some semantic release versions incrementing, I'll make a build of this with a hard coded, earlier version number—and the alert should display. 

Once it's merged, though, it should quite often show up so also good to test in the wild.

**Comment by markmhx** [comment]
I'll approve this on my end then, with the idea that I'll be looking for it in future builds.

**Review by markmhx — APPROVED** [review]

**Pull request merged**
