### PR TITLE
Fix/stacking err state

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/465608064)

### CODE REVIEW

**Comment by markmhx** [comment]
@kyranjamie ready for review?

**Comment by markmhx** [comment]
Getting a blank screen upon open, and I _think_ I hear my mac's fan spin up briefly: 🌬️ 

Screen Shot 2021-01-04 at 14 48 14

**Comment by kyranjamie** [comment]
Sorry @markmhx this issue was fixed upstream, rebase has fixed it. Please try with latest download build link

**Comment by kyranjamie** [comment]
Merged this into beta6 so it can be tested alongside other changes.

**Pull request merged**
