### PR TITLE
feat: add new STX icon, description

### LINKED ISSUE #247: Stacks Wallet 2.0 app icons
The previous wallet used an unpadded Blockstack logo as the app icon, which results in an app icon larger than all its surrounding icons (MacOS).

The new wallet needs an application [icon, ideally inline with the MacOS Big Sur app icon guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/).

[Here's a figma template with the Big Sur rulers](https://www.figma.com/file/ddzopOSknzKKU8EveMHVpk/macOS-Big-Sur-Icon-Template-Community?node-id=0%3A1).

You can find some more information on the [assets required for each platform on the Electron builder website](https://www.electron.build/configuration/configuration)

Considerations, especially around icon padding, need to be taken for other platforms, though we can likely reuse the icons.

Hope you like my attempt we'll use in the meantime

image

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/452650443)

image

@whoabuddy: Would you be able to install this build and check #263 is addressed? 

Wallet now installs to different directories
```
❯ ll ~/Library/Application\ Support/ | grep stacks
drwx------     - kyran 23 Dec 18:01  StacksWallet
drwx------     - kyran 23 Dec 17:59  StacksWalletTestnet
```

### CODE REVIEW

**Comment by markmhx** [comment]
Icon looks fantastic 🔥

**Comment by markmhx** [comment]
I'm curiously getting a different icon on MacOS:

image

**Comment by whoabuddy** [comment]
@kyranjamie sorry for the delay on getting back to you for this one, do I just grab the latest `Download the latest builds.` link and test from there?

**Comment by kyranjamie** [comment]
Sorry @whoabuddy—if you can hang fire testing this. Github actions is having all kinds of trouble building the releases properly.

**Comment by whoabuddy** [comment]
I removed my old 4.0.0-beta3 wallet and tested this out today:

## Mainnet Linux Version

- installer still shows `.` in the description for the .deb file

20201223_006_Selection

- package install failed because I have the older v3 wallet installed:

```bash
Selecting previously unselected package stacks-wallet.
(Reading database ... 
...
(Reading database ... 100%%
(Reading database ... 387229 files and directories currently installed.)
Preparing to unpack .../stacks-wallet.deb ...
Unpacking stacks-wallet (4.0.0-beta.8) ...
dpkg: error processing archive /home/absorb/Desktop/stacks-wallet-4.0.0-mainnet-linux/stacks-wallet.deb (--install):
 trying to overwrite '/opt/Stacks Wallet/LICENSE.electron.txt', which is also in package stacks-wallet-1 3.0.0
dpkg-deb (subprocess): decompressing archive member: lzma write error: Broken pipe
dpkg-deb: error: <decompress> subprocess returned error exit status 2
dpkg-deb (subprocess): cannot copy archive member from '/home/absorb/Desktop/stacks-wallet-4.0.0-mainnet-linux/stacks-wallet.deb' to decompressor pipe: failed to write (Broken pipe)
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for desktop-file-utils (0.23+linuxmint5) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
```

## Testnet Linux Version

- same `.` in installer description
- installed successfully
- listed in start menu but no icon
*(using Linux Mint 19 w/ Cinnamon)*

20201223_008_Selection

- accepted terms and conditions
- chose "I already have secret key"
  - trying to right-click paste in key and no menu comes up. it flashes a cursor change really quick.
  - ctrl+v still works :)
- set my password
- realized I used the wrong key, tried reset wallet - back to terms and conditions
- was able to walk through all again no problem
- wallet is working!

20201223_009_Selection

**Pull request merged**
