### PR TITLE
feat: stacks/ui

### PR DESCRIPTION
**Pull request by aulneau**
> _Build failed, [see here for details](https://github.com/blockstack/stacks-wallet/actions/runs/416235190)_

This updates the UI deps to use `@stacks/ui` and emotion.

### CODE REVIEW

**Comment by kyranjamie** [comment]
Thanks @aulneau 

I get this error when navigating to the settings page now

```
react-dom.development.js:68 Warning: React does not recognize the `variantColor` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `variantcolor` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at button
    at EmotionCssPropInternal (http://localhost:1212/dist/renderer.dev.js:38760:73)
    at http://localhost:1212/dist/renderer.dev.js:79716:22
    at Button (http://localhost:1212/dist/renderer.dev.js:80043:26)
    at div
    at EmotionCssPropInternal (http://localhost:1212/dist/renderer.dev.js:38760:73)
    at http://localhost:1212/dist/renderer.dev.js:79716:22
    at ButtonGroup (http://localhost:1212/dist/renderer.dev.js:79951:19)
    at div
    at EmotionCssPropInternal (http://localhost:1212/dist/renderer.dev.js:38760:73)
    at http://localhost:1212/dist/renderer.dev.js:79716:22
    at TxModalFooter (http://localhost:1212/dist/renderer.dev.js:10111:3)
    at div
    at EmotionCssPropInternal (http://localhost:1212/dist/renderer.dev.js:38760:73)
    at http://localhost:1212/dist/renderer.dev.js:79716:22
    at http://localhost:1212/dist/renderer.dev.js:84140:25
    at form
    at EmotionCssPropInternal (http://localhost:1212/dist/renderer.dev.js:38760:73)
    at http://localhost:1212/dist/renderer.dev.js:79716:22
    at http://localhost:1212/dist/renderer.dev.js:84193:27
    at div
    at EmotionCssPropInternal (http://localhost:1212/dist/renderer.dev.js:38760:73)
    at http://localhost:1212/dist/renderer.dev.js:79716:22
    at ModalWrapper (http://localhost:1212/dist/renderer.dev.js:84169:22)
    at http://localhost:1212/dist/renderer.dev.js:84216:37
    at UpsertStacksNodeSettingsModal (http://localhost:1212/dist/renderer.dev.js:10812:5)
    at section
    at EmotionCssPropInternal (http://localhost:1212/dist/renderer.dev.js:38760:73)
    at http://localhost:1212/dist/renderer.dev.js:79716:22
    at SettingSection (http://localhost:1212/dist/renderer.dev.js:6392:3)
    at div
    at EmotionCssPropInternal (http://localhost:1212/dist/renderer.dev.js:38760:73)
    at http://localhost:1212/dist/renderer.dev.js:79716:22
    at div
    at EmotionCssPropInternal (http://localhost:1212/dist/renderer.dev.js:38760:73)
    at http://localhost:1212/dist/renderer.dev.js:79716:22
    at Screen
    at SettingsLayout (http://localhost:1212/dist/renderer.dev.js:33043:3)
    at Settings (http://localhost:1212/dist/renderer.dev.js:33158:83)
    at Route (eval at ES6ProxyComponentFactory (http://localhost:1212/dist/renderer.dev.js:147113:10), <anonymous>:14:7)
    at Switch (eval at ES6ProxyComponentFactory (http://localhost:1212/dist/renderer.dev.js:147113:10), <anonymous>:14:7)
    at App (http://localhost:1212/dist/renderer.dev.js:30891:3)
    at Routes (http://localhost:1212/dist/renderer.dev.js:35300:77)
    at Router (eval at ES6ProxyComponentFactory (http://localhost:1212/dist/renderer.dev.js:147113:10), <anonymous>:14:7)
    at ConnectedRouter (eval at ES6ProxyComponentFactory (http://localhost:1212/dist/renderer.dev.js:147113:10), <anonymous>:14:7)
    at ConnectedRouterWithContext (http://localhost:1212/dist/renderer.dev.js:100199:25)
    at Connect(ConnectedRouterWithContext) (http://localhost:1212/dist/renderer.dev.js:150959:75)
    at PersistGate (eval at ES6ProxyComponentFactory (http://localhost:1212/dist/renderer.dev.js:147113:10), <anonymous>:14:7)
    at Provider (http://localhost:1212/dist/renderer.dev.js:150672:20)
    at ThemeProvider (http://localhost:1212/dist/renderer.dev.js:38794:71)
    at ThemeProvider (http://localhost:1212/dist/renderer.dev.js:84999:25)
    at Root (http://localhost:1212/dist/renderer.dev.js:32916:3)
    at AppContainer (eval at ES6ProxyComponentFactory (http://localhost:1212/dist/renderer.dev.js:147113:10), <anonymous>:14:7)
    at HotExportedRoot (eval at ES6ProxyComponentFactory (http://localhost:1212/dist/renderer.dev.js:147113:10), <anonymous>:14:7)
    at AppContainer (eval at ES6ProxyComponentFactory (http://localhost:1212/dist/renderer.dev.js:147113:10), <anonymous>:14:7)
    at ThemeProvider (http://localhost:1212/dist/renderer.dev.js:38794:71)
    at ThemeProvider (http://localhost:1212/dist/renderer.dev.js:84999:25)```

**Comment by aulneau** [comment]
Yep there are some type related fixes we will need to do now

**Comment by kyranjamie** [comment]
Thanks @aulneau, will get to testing/reviewing this when #331 is merged, today I hope

**Comment by aulneau** [comment]
@timstackblock would you be able to pull this down and ensure that nothing looks off in both light and dark mode?

**Comment by kyranjamie** [comment]
> Thanks @aulneau, will get to testing/reviewing this when #331 is merged, today I hope

Update, I didn't get to it today 😅 . These changes are appreciated and will be incorporated asap, but there are a few higher priority things to get to first.

**Comment by markmhx** [comment]
@kyranjamie will hand-merge these changes into another branch

**Comment by andresgalante** [comment]
Closes #625

**Pull request closed without merging**
