### PR TITLE
feat: terms screen, closes #171

### LINKED ISSUE #171: Add Terms of Use prompt for new Stacks Wallet
Show this prompt every time the user loads the wallet for the first time on a device. Legal needs to review content before release.

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/424069982).
This will be version  when merged into `master`

image

- [ ] Review content
- [ ] Implement close action

### CODE REVIEW

**Comment by markmhx** [comment]
Looks good, though the scrollbar isn't displayed for me by default, and given the copy happens not to get cut off vertically, it could be easy to assume it doesn't scroll. Is there any good way to indicate this without forcing the user to scroll before confirming?

image

**Comment by kyranjamie** [comment]
@markmhx No scrollbars because you're not using a mouse, presumably. We could just remove the inner container so the user has to scroll past everything to get to the actions?

**Comment by kyranjamie** [comment]
@markmhx ready to rereview

**Review by markmhx — APPROVED** [review]
LGTM generally, I'd just suggest a bit of padding for narrow viewports 

image

**Pull request merged**
