### PR TITLE
fix: display total balance, not available, 

### LINKED ISSUE #829: Wallet displays unlocked amount as total balance
Total balance shows available, instead of total.

Should show total here, only shows available, can't see total wo going to explorer, scared me haha!

Bug found testing Stacks Wallet build undefined, 4.2.0.

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/967761098)

Closes #829

Displays total balance less any pending outbound transactions.

@cuevasm Would you be able to test this build?

### CODE REVIEW

**Comment by markmhx** [comment]
Will the "available" amount now show the quantity of STX available as unlocked by the "legacy" unlocking schedule _less_ any STX that are currently locked for Stacking?

**Review by fbwoolf — APPROVED** [review]

**Comment by kyranjamie** [comment]
> Will the "available" amount now show the quantity of STX available as unlocked by the "legacy" unlocking schedule less any STX that are currently locked for Stacking?

This just subtracts the values coming from the API. The `locked` property only includes stacked tokens.

**Comment by markmhx** [comment]
So if I understand things here, and I have for example:

- 300,000 STX total
- 150,000 locked for legacy unlocking schedule
- 100,000 STX locked for Stacking

Then it'll say "200,000 STX available". But if I go to send 200,000 STX, it'll throw an error since only 50,000 STX are actually unlocked between both Stacking and the legacy unlocking schedule. Is that correct?

Ideally it'd say "50,000 STX available" to avoid this circumstance and potential confusion. And once Stacking ends and those related 100,000 STX unlocked (all else equal), it should say "150,000 STX available".

**Comment by kyranjamie** [comment]
@markmhx is this blocking for this PR? We've never supported vested scheduled in the desktop wallet, though I totally agree we should https://github.com/blockstack/stacks-wallet/issues/453

**Comment by markmhx** [comment]
There's no need to block this PR. Let's address in https://github.com/blockstack/stacks-wallet/issues/453 as you suggest.

**Pull request merged**
