### PR TITLE
Release/4.1.2

### LINKED ISSUE #591: Factor pending transactions into balance and "Send Max" calculation
I used the Hiro Wallet 4.0.4 to send a tx and used the "Send Max" button. The transaction ended up stuck in the mempool with the reason being "Insufficient Balance". It looks like the wallet didn't calculate the appropriate fee... instead it sent the max funds without subtracting the expected fee first. I'm not a dev so don't know if these details are helpful, but id just moments earlier submitted a smaller tx from the same wallet that worked and confirmed just fine. I was also sending this from a ledger. Not sure  if those details help.

### LINKED ISSUE #636: Fix hard coded cycle time information in stacking flow

### LINKED ISSUE #649: Display relevant error message when user tries to revoke delegation without sufficient balance
Bug found testing Stacks Wallet build undefined, 4.1.0.

I have delegated STX here:
https://explorer.stacks.co/txid/0xe225a0f01f094ad24619307ca08304106f5d345bbb33d56060ae30941d8cdc99?utm_source=stacks-wallet&chain=mainnet

While trying to revoke delegation using the button/link in the desktop wallet, the process repeatedly fails with:
Unable to verify transaction Failed to call stacking contract
image

### LINKED ISSUE #657: [4.1.0] Bug: Pending transaction
The pending transaction is over 24 hours old, it's weird and very long.

Transaction ID:
0xd2921a84cb29eff672a9538a9f4764886c58b7ea60c83979ca384f54025b86cb
изображение

### LINKED ISSUE #691: Add indicator that until-burn-ht has been passed for Stacking delegation
@kyranjamie 

I think there is an issue with the burn height PR.

I delegated in the image below and set the burn height to 1 cycle it should have revoked automatically at block 1940070, but it did not as you can see from the image below it is still delegated and I will have to revoke manually. 

Here is the delegation contract call
https://explorer.stacks.co/txid/0x3318a26a5b50c5410382574a691bb0fe395bf311c1cfc2ea25f20ecbbf42aea6?utm_source=stacks-wallet&chain=testnet

Screen Shot 2021-03-12 at 10 11 44 AM

Screen Shot 2021-03-13 at 8 53 07 AM

### LINKED ISSUE #696: Delegation status query doesn't respect selected node
There's an issue where requests to the API are made to **both** the previously selected node, and the current one. 

This is likely an issue with `useSWR`, or the application of it.

### LINKED ISSUE #700: Add custom Stacks Blockchain API headers
The Wallet should set product name and version request headers.

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/711148173)

Closes #591
Closes #636
Closes #649
Closes #657
Closes #691
Closes #696
Closes #700 

Hiding comments relating to resolved issues.

### CODE REVIEW

**Comment by markmhx** [comment]
I'm testing the following cases:

- [ ] Confirm accurate cycle duration value in copy on Stacking form ("One cycle typically lasts N, depending on the Bitcoin block time") (https://github.com/blockstack/stacks-wallet/issues/636)
- [ ] Send STX with "Max" option once transaction is already pending and confirm proper calculation of remaining STX minus pending transaction (https://github.com/blockstack/stacks-wallet/issues/591)
- [ ] Attempt to revoke delegation without unlocked tokens and confirm appropriate error message (https://github.com/blockstack/stacks-wallet/issues/649)
- [ ] Delegate with until-burn-hit value and confirm appropriate warning message appears once burn height reached (https://github.com/blockstack/stacks-wallet/issues/691)
- [ ] Configure different node and confirm requests made only to new API (https://github.com/blockstack/stacks-wallet/issues/696)
- [ ] Inspect headers sent to API across sample of calls for `x-hiro-product` and `x-hiro-version`
- [ ] Test Trezor help URL for hiro.so domain usage
- [ ] Confirm display of "The pool has indefinite permission to lock your STX for up to 12 cycles at a time" in delegation form

I'm planning to execute these on MacOS. @kyranjamie do you think the changes here warrant testing on Windows and Linux as well given possible differences on those platforms?

**Comment by markmhx** [comment]
@kyranjamie I'm getting 4.1.1 builds when installing via the [link above](https://github.com/blockstack/stacks-wallet/actions/runs/687397382) 🤔 

I tried downloading and installing twice but same thing:

image


image

**Comment by aulneau** [comment]
@markmhx I don't think the version was bumped in package.json, so it would still read at 4.1.1

**Comment by kyranjamie** [comment]
@markmhx Expected, for now. Technically the version is only incremented manually by semantic-release on merge. For dev builds we should hide the version number.

**Comment by markmhx** [comment]
Hmm I was confused since I ran into the same bug as reported in https://github.com/blockstack/stacks-wallet/issues/591 out of the gate. I'll test it again and see what happens.

**Comment by markmhx** [comment]
I seem blocked on testing here until https://github.com/blockstack/stacks-wallet/issues/716 is resolved or testnet becomes operational again.

**Comment by markmhx** [comment]
The delegation form should say "The pool has indefinite permission to lock your STX for up to 12 cycles at a time" here for greater precision:

image

**Review by markmhx — APPROVED** [review]

**Pull request merged**
