### PR TITLE
fix: nonce calulcation including coinbase

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/786327159)

@yknl I've updated logic here, but the original implementation doesn't quite work as I originally thought & described—it looks like it should work as we need, no? 🤔 

Incrementing 1 from the highest current nonce of pending txs, or using the current one.

### CODE REVIEW

**Comment by yknl** [comment]
I think the nonce calculation would be correct, but does this re-enable the send button?

**Comment by kyranjamie** [comment]
> I think the nonce calculation would be correct, but does this re-enable the send button?

No, it doesn't. Don't fully understand this issue though. How would the balance be wrong? And, even if miners not being able to send while they have pending txs is an issue, is it greater than novices sending balances they don't? 🤔  Maybe another solution is needed than just reenabling the send button. 

Min balance calculation here

https://github.com/blockstack/stacks-wallet/blob/05e053a99bdd7e334836581ea3a8d66612a4965f/app/hooks/use-balance.ts#L23-L27

**Comment by kyranjamie** [comment]
@yknl can you rereview, I've updated with logic to not include nonce values < account nonce in what are considered outbound txs, resulting in these txs not being subtracted from total.

**Review by yknl — APPROVED** [review]
Logic looks correct to me 👍

**Comment by andresgalante** [comment]
Now that we have @yknl thumb up, @kyranjamie or @aulneau can we merge this?

**Pull request merged**
