### PR TITLE
Release/4.1.1

### PR DESCRIPTION
**Pull request by kyranjamie**
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/654432170)

### CODE REVIEW

**Comment by unclemantis** [comment]
Will wait until after Cycle 4 to update.

**Comment by markmhx** [comment]
@kyranjamie Any particular aspects of this build you still need me to review?

Once the latest build is ready, I'll delegate STX on testnet then revoke immediately to see if I run into any issues. I believe I've provided all copy input already though.

**Comment by kyranjamie** [comment]
@markmhx Thanks, yeah just a quick run through.

I noticed I'd committed some code needed for the electron update that breaks layouts 🤦🏼

**Comment by markmhx** [comment]
Copy tweak: "...possible to lock your STX longer..."

image

Another copy tweak: "This address is provided to you by your chosen pool for Stacking delegation specifically."

image

And we still need to make these copy changes in general to the bottom section (note: ignore the red arrow):

Screen_Shot_2021-03-11_at_14 02 41

**Comment by markmhx** [comment]
Another nit:

"Have a chance to earn BTC **by locking** your STX temporarily"

image

**Review by markmhx — APPROVED** [review]

**Pull request merged**
